const FLOWS = {
  BIENVENIDA: {
    NAME: "BIENVENIDA",
    STEPS: {
      SALUDO_INICIAL: "SALUDO_INICIAL",
      ESPERANDO_NOMBRE: "ESPERANDO_NOMBRE",
      MENU: "MENU",
      ESPERANDO_OPCION: "ESPERANDO_OPCION",
      PREGUNTAR_TIPO_USUARIO: "PREGUNTAR_TIPO_USUARIO",
      ESPREANDO_TIPO_USUARIO: "ESPREANDO_TIPO_USUARIO",
    },
  },
  REQUISITOS: {
    NAME: "REQUISITOS",
    STEPS: {
      REQUISITOS_INICIAL: "REQUISITOS_INICIAL",
      ENVIANDO_REQUISITOS: "ENVIANDO_REQUISITOS",
      ESPERANDO_TIPO_PRESTAMO: "ESPERANDO_TIPO_PRESTAMO",
    },
  },
  PREGUNTAS_FRECUENTES: {
    NAME: "PREGUNTAS_FRECUENTES",
    STEPS: {
      PREGUNTAS_FRECUENTES_INICIAL: "PREGUNTAS_FRECUENTES_INICIAL",
      ENVIANDO_PREGUNTAS_FRECUENTES: "ENVIANDO_PREGUNTAS_FRECUENTES",
    },
  },
  ASESOR: {
    NAME: "ASESOR",
    STEPS: {
      ASESOR_INICIAL: "ASESOR_INICIAL",
    },
  },
  SIMULACION: {
    NAME: "SIMULACION",
    STEPS: {
      SIMULACION_INICIAL: "SIMULACION_INICIAL",
    },
  },
  COMPROBANTE: {
    NAME: "COMPROBANTE",
    STEPS: {
      COMPROBANTE_INICIAL: "COMPROBANTE_INICIAL",
    },
  },
  LLENADO_SOLICITUD: {
    NAME: "LLENADO_SOLICITUD",
    STEPS: {
      LLENADO_SOLICITUD_INICIAL: "LLENADO_SOLICITUD_INICIAL",
    },
  },
  // AGREGAR MAS FLUJOS/PASOS
};

const USUARIOS = {
  PENSIONADO: "PENSIONADO",
  ACTIVO: "ACTIVO",
};
const GLOBAL_COMMANDS = ["menu", "inicio", "cancelar"];

module.exports = {
  FLOWS,
  GLOBAL_COMMANDS,
  USUARIOS,
};
