const FLOWS = {
  BIENVENIDA: {
    NAME: "BIENVENIDA",
    STEPS: {
      SALUDO_INICIAL: "SALUDO_INICIAL",
      ESPERANDO_NOMBRE: "ESPERANDO_NOMBRE",
      MENU:"MENU",
      PREGUNTAR_TIPO_USUARIO:"PREGUNTAR_TIPO_USUARIO",
    },
  },
  REQUISITOS: {
    NAME: "REQUISITOS",
    STEPS: {
      REQUISITOS_INICIAL: "REQUISITOS_INICIAL",
      ENVIANDO_REQUISITOS: "ENVIANDO_REQUISITOS",
    },
  },
  // AGREGAR MAS FLUJOS/PASOS
};

const GLOBAL_COMMANDS = ["menu", "inicio", "cancelar"];

module.exports = {
  FLOWS,
  GLOBAL_COMMANDS,
};
