/**
 * Configuration constants for the chatbot
 * @module constants
 */

/**
 * Flow definitions for the chatbot conversation flows
 * Each flow represents a distinct conversation path with multiple steps
 */
const FLOWS = {
  BIENVENIDA: {
    NAME: "BIENVENIDA",
    STEPS: {
      SALUDO_INICIAL: "SALUDO_INICIAL",
      ESPERANDO_NOMBRE: "ESPERANDO_NOMBRE",
      MENU: "MENU",
      ESPERANDO_OPCION: "ESPERANDO_OPCION",
      PREGUNTAR_TIPO_USUARIO: "PREGUNTAR_TIPO_USUARIO",
      ESPERANDO_TIPO_USUARIO: "ESPERANDO_TIPO_USUARIO",
    },
  },
  REQUISITOS: {
    NAME: "REQUISITOS",
    STEPS: {
      REQUISITOS_INICIAL: "REQUISITOS_INICIAL",
      ENVIANDO_REQUISITOS: "ENVIANDO_REQUISITOS",
      ESPERANDO_TIPO_PRESTAMO: "ESPERANDO_TIPO_PRESTAMO",
    },
  },
  PREGUNTAS_FRECUENTES: {
    NAME: "PREGUNTAS_FRECUENTES",
    STEPS: {
      PREGUNTAS_FRECUENTES_INICIAL: "PREGUNTAS_FRECUENTES_INICIAL",
      ENVIANDO_PREGUNTAS_FRECUENTES: "ENVIANDO_PREGUNTAS_FRECUENTES",
    },
  },
  ASESOR: {
    NAME: "ASESOR",
    STEPS: {
      ASESOR_INICIAL: "ASESOR_INICIAL",
      CHAT_SUSPENDIDO: "CHAT_SUSPENDIDO",
    },
  },
  SIMULACION: {
    NAME: "SIMULACION",
    STEPS: {
      SIMULACION_INICIAL: "SIMULACION_INICIAL",
      SIMULACION_CREDENCIAL: "SIMULACION_CREDENCIAL",
      VALIDACION_CREDENCIAL: "VALIDACION_CREDENCIAL",
    },
  },
  COMPROBANTE: {
    NAME: "COMPROBANTE",
    STEPS: {
      COMPROBANTE_INICIAL: "COMPROBANTE_INICIAL",
    },
  },
  LLENADO_SOLICITUD: {
    NAME: "LLENADO_SOLICITUD",
    STEPS: {
      LLENADO_SOLICITUD_INICIAL: "LLENADO_SOLICITUD_INICIAL",
      RECIBIR_CREDENCIAL: "RECIBIR_CREDENCIAL",
      PROCESAR_INFO_MANUALMENTE: "PROCESAR_INFO_MANUALMENTE",
      CONFIRMAR_INFORMACION: "CONFIRMAR_INFORMACION",
      PROCESAR_CREDENCIAL: "PROCESAR_CREDENCIAL",
      LLENADO_SOLICITUD_PDF: "LLENADO_SOLICITUD_PDF",
    },
  },
  // Add more flows and steps as needed
};

/**
 * User types for the chatbot
 */
const USUARIOS = {
  PENSIONADO: "PENSIONADO",
  ACTIVO: "ACTIVO",
};

/**
 * Global commands that can be used at any point in the conversation
 * to return to the main menu
 */
const GLOBAL_COMMANDS = ["menu", "inicio", "cancelar"];

module.exports = {
  FLOWS,
  GLOBAL_COMMANDS,
  USUARIOS,
};
